Add docs for Write-Only Replica Staging and create_aip_replicas command
artefactual/archivematica-storage-service-docs pull request #48
Opened 2021-06-08 18:50 UTC by tw4l

Connected to https://github.com/archivematica/issues/issues/1440

2021-06-14 13:00 UTC, sarah-mason requested changes
Looks great! Makes sense and I only have to _tiny_ changes to make.

2021-06-14 13:00 UTC, sarah-mason commented on administrators.rst
> +   Replicator location in an Write-Only Replica Staging space cannot
```suggestion
   Replicator location in a Write-Only Replica Staging space cannot
```

2021-06-14 13:00 UTC, sarah-mason commented on administrators.rst
> +Replicas can also be be created and updated in bulk and without the need for
```suggestion
Replicas can also be created and updated in bulk without the need for
```

2021-06-14 19:14 UTC, tw4l commented
Thanks @sarah-mason! The requested changes have been made and I added a note about the flat storage structure for this space.

2021-07-02 20:12 UTC, sromkey commented
Just a reminder to merge :)

2021-07-05 14:18 UTC, tw4l commented
@sarah-mason friendly reminder to re-review :) thanks!

2021-07-19 09:50 UTC, sarah-mason approved these changes
Sorry it took me so long to re-review @tw4l! I must have missed the notification. Looks great though!

2021-07-19 15:05 UTC, merged