Add rclone Space documentation
artefactual/archivematica-storage-service-docs pull request #52
Opened 2022-08-29 16:27 UTC by tw4l

Related to https://github.com/archivematica/Issues/issues/1567

This PR adds information for the RClone Space/access protocol to the Storage Service documentation.

The test CI is failing for this and the newly-created 0.20 branch, which is currently a copy of 0.19, which was previously passing. I think it might have to do with the version of Sphinx installed in the test CI (`Sphinx==5.1.1`), as it's building fine locally for me with `Sphinx==4.0.2` and I see some warnings related to string formatting in the CI output.

2022-08-30 10:32 UTC, scollazo requested changes

2022-08-30 10:32 UTC, scollazo commented on administrators.rst
> +RClone is available as an access protocol in Storage Service 0.20 and higher.
I think it's worth to add more context, and telling what rclone actually is.
```suggestion
Rclone is a command-line program to manage files on cloud storage, and is available as an access protocol in Storage Service 0.20 and higher.
```

2022-08-30 10:32 UTC, scollazo commented on administrators.rst
> +Configuration of details such as access keys is via environment variables.
```suggestion
Configuration of details such as access keys can be made through a configuration file, or via environment variables (the recommended method).
```

2022-08-30 18:22 UTC, tw4l commented
@scollazo nice suggestions, thanks! changes made

2022-09-13 05:35 UTC, sevein approved these changes

2022-09-13 05:36 UTC, sevein commented
Thanks!

2022-09-13 15:13 UTC, scollazo approved these changes
LGTM!

2022-09-13 15:19 UTC, merged